M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Sun 18 Dec 2022 03:13:10 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-18T15:13:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.15Y-2.4
X2.15Y-4.0
X5.925Y-2.4
X5.925Y-4.0
T0
M30
